### ISSUE TITLE
Bareword found where operator expected at ./Makefile.PL line 1, near "30 mtime"

### ISSUE THREAD

**Issue by pali** [Dual-Life/Devel-PPPort#183]
Devel::PPPort 3.57 cannot be installed on more machines due to following error:
```
Checking if your kit is complete...
Looks good
Setting license tag...
Adding META_MERGE...
Bareword found where operator expected at ./Makefile.PL line 1, near "30 mtime"
	(Missing operator before mtime?)
Unquoted string "mtime" may clash with future reserved word at ./Makefile.PL line 1.
ERROR from evaluation of /home/cpan/.cpan/build/Devel-PPPort-3.57-0/PaxHeader/Makefile.PL: syntax error at ./Makefile.PL line 1, near "30 mtime"
```

http://www.cpantesters.org/cpan/report/5c0dbcfa-47ec-11ea-855f-ba15fa75da41
http://www.cpantesters.org/cpan/report/4ea6861a-45de-11ea-a030-f8d83ca39aa3
http://www.cpantesters.org/cpan/report/3fec7ad8-45db-11ea-a030-f8d83ca39aa3

**Comment by khwilliamson** [comment]
I don't see where that is coming from.

**Comment by pali** [comment]
Now I see where is the problem! Look at the last line from error output.

`ERROR from evaluation of /home/cpan/.cpan/build/Devel-PPPort-3.57-0/PaxHeader/Makefile.PL: syntax error at ./Makefile.PL line 1, near "30 mtime"`

It is from file `Devel-PPPort-3.57-0/PaxHeader/Makefile.PL`. When Devel-PPPort was extracted from TAR file is created `PaxHeader` directory which contains extended attributes.

This is classic problem that TAR archive contains some stupid extended attributes which are not supported by older version of /bin/tar programs which treats them as directories and files.

I suggest to create a new proper release of Devel-PPPort without those fancy extended attributes in TAR to prevent these problems.

**Comment by pali** [comment]
See also: https://huntingbears.nl/2015/02/17/new-tar-paxheaders-and-installing-from-cpan/

**Comment by atoomic** [comment]
We are going to do a release and I'm going to check that the tarball is clean
probably also add an additional check

From @pali 

this should be fixed, tarball for such critical distribution which should run on older Perl versions should not use any extended PAX headers

```
$ wget -q https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/Devel-PPPort-3.57_02.tar.gz -O - | gunzip | grep -q PaxHeader && echo "contains PaxHeader"
```
