### ISSUE TITLE
Enhancement: add the concept of __REDEFINE__

### ISSUE THREAD

**Issue by atoomic** [Dual-Life/Devel-PPPort#226]
The idea here is to introduce a new macro `__REDEFINE__` which would do the `#undef` and `redefinition` of the macro
this could then be used in multiple locations to simplify code like this

```c
#if { VERSION < 5.27.7 }
#undef dNOOP
 __UNDEFINED__ dNOOP struct Perl___notused_struct
#endif
```

to

```c
#if { VERSION < 5.27.7 }
__REDEFINE__ dNOOP struct Perl___notused_struct
#endif
```

**Comment by khwilliamson** [comment]
patches welcome
