### ISSUE TITLE
Bump MAX_PERL to 5.26? 

### ISSUE THREAD

**Issue by wolfsage** [Dual-Life/Devel-PPPort#45]
Need to remember to update this more often somehow...

**Comment by jkeenan** [comment]
@wolfsage , @khwilliamson , Currently, in Perl 5 core, we have:
```perl
$data =~ s{__MAX_PERL__}{5.20}g;
```
Can this be bumped to 5.26?

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
It has now been bumped to 5.30, and a warning added to the Makefile to be sure it is correct.
