### ISSUE TITLE
broken SvRXOK defined without NEED_SvRX

### ISSUE THREAD

**Issue by haarg** [Dual-Life/Devel-PPPort#46]
On perl 5.8.9, where SvRX and SvRXOK don't exist, SvRXOK will be defined but broken if NEED_SvRX is not set.  This caused an issue for Moose, because it had its own definition of SvRXOK, but ppport's new broken implementation began taking priority.

**Comment by karenetheridge** [comment]
workaround in https://github.com/moose/Moose/commit/68289068dc458b1c3f8e203c91122b657c83a399

SvRX was added in https://github.com/mhx/Devel-PPPort/commit/a6a4d2b6597f06b61fc93e9521ccc3fc761a63e1

**Comment by khwilliamson** [comment]
I have looked at this, and I don't think there is a good solution.  The two options I see are to always effectively define NEED_SvRX internally in PPPort for 5.8.9 and whatever other releases are affected; or to document the situation.

I have a similar situation I need to get into PPPort, where macros call helper functions.  For this, I think the only reasonable solution is to document what to do in ppport.h

**Comment by khwilliamson** [comment]
haarg, do you have any comments about my solution of always defining NEED_SvRX for 5.8.9

**Comment by haarg** [comment]
There are three options that make sense to me:

  1. Always define SvRX (if needed) where SvRXOK is also defined, ignoring NEED_SvRX.
  2. Add a NEED_SvRXOK define, which controls the definition of SvRXOK.
  3. Have SvRXOK controlled by the NEED_SvRX define.

The first seems like it is likely the simplest and least likely to cause problems.

**Comment by khwilliamson** [comment]
Looking at the code SvRX is no longer a function, but a macro that doesn't need a NEED_SvRX, so I'm closing this ticket.
