### ISSUE TITLE
Expects dot to be in @INC

### ISSUE THREAD

**Issue by khwilliamson** [Dual-Life/Devel-PPPort#49]
This is no longer the case in 5.25.something and later.

If I change several (perhaps it's all) require statements to explicitly ask for ./foo, I can get it to work.  But I'm not sure if there is a better solution.  I can create a PR for what I've done.

**Comment by jkeenan** [comment]
@khwilliamson I suspect you made modifications necessary to resolve this issue when you recently did work on Devel-PPPort in the Perl 5 core.  If correct, is this issue closable?

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
On 02/24/2018 12:12 PM, James E Keenan wrote:
> @khwilliamson <https://github.com/khwilliamson> I suspect you made 
> modifications necessary to resolve this issue when you recently did work 
> on Devel-PPPort in the Perl 5 core. If correct, is this issue closable?

Actually, I didn't look at anything besides moving the directories from 
cpan to dist, and handling the fallout.  I would have hoped that this 
would have been fixed much earlier than that; I have not looked at the code.

**Comment by khwilliamson** [comment]
But things seem to be working.  If no one comments to the contrary, next time I'm here, I'll close it.  Or others, after a suitable interval, feel free to close it.

**Comment by karenetheridge** [comment]
I believe this was fixed in release 3.36 (2017-05-14).
