### ISSUE TITLE
Devel::PPPort: Fix commit d6d4687 vmess is already

### ISSUE THREAD

**Issue by atoomic** [Dual-Life/Devel-PPPort#61]
Attached patch fixes commit d6d4687 as Devel::PPPort's vmess was already implemented as part of commit f87c37b.

RT #134101 https://rt.perl.org/Public/Bug/Display.html?id=134101
author: pali

**Comment by khwilliamson** [comment]
I think this can be closed

**Comment by khwilliamson** [comment]
No response in 6 months.  Closing
