### ISSUE TITLE
Use AppVeyor CI for Windows testing

### ISSUE THREAD

**Issue by pali** [Dual-Life/Devel-PPPort#97]

**Comment by atoomic** [comment]
I already use some AppVeyor config on some projects but have also heard that TravisCI is also supporting windows now, maybe we can use the same CI?

https://docs.travis-ci.com/user/reference/windows/

**Comment by pali** [comment]
I was not able to use Travis Windows builds with different Perl versions yet.

If you want to use AppVeyor with different Perl versions, you can look at my configuration for Exception::Class::Try::Catch: https://github.com/pali/Exception-Class-Try-Catch/blob/master/.appveyor.yml
There are about 10 different perl versions and each in both 32bit and 64bit version.

**Comment by atoomic** [comment]
basic workflow setup thanks
https://ci.appveyor.com/project/atoomic/devel-ppport
